/* eslint linebreak-style: ["error", "unix"] */
/* eslint linebreak-style: ["error", "windows"] */
const keysObj = {
  // first row
  Backquote: {
    textRu: 'ё',
    textEn: '`',
    textShiftRu: 'Ё',
    textShiftEn: '~',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit1: {
    textRu: '1',
    textEn: '1',
    textShiftRu: '!',
    textShiftEn: '!',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit2: {
    textRu: '2',
    textEn: '2',
    textShiftRu: '"',
    textShiftEn: '@',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit3: {
    textRu: '3',
    textEn: '3',
    textShiftRu: '№',
    textShiftEn: '#',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit4: {
    textRu: '4',
    textEn: '4',
    textShiftRu: ';',
    textShiftEn: '$',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit5: {
    textRu: '5',
    textEn: '5',
    textShiftRu: '%',
    textShiftEn: '%',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit6: {
    textRu: '6',
    textEn: '6',
    textShiftRu: ':',
    textShiftEn: '^',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit7: {
    textRu: '7',
    textEn: '7',
    textShiftRu: '?',
    textShiftEn: '&',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit8: {
    textRu: '8',
    textEn: '8',
    textShiftRu: '*',
    textShiftEn: '*',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit9: {
    textRu: '9',
    textEn: '9',
    textShiftRu: '(',
    textShiftEn: '(',
    width: 6,
    height: 4,
    row: 1,
  },
  Digit0: {
    textRu: '0',
    textEn: '0',
    textShiftRu: ')',
    textShiftEn: ')',
    width: 6,
    height: 4,
    row: 1,
  },
  Minus: {
    textRu: '-',
    textEn: '-',
    textShiftRu: '_',
    textShiftEn: '_',
    width: 6,
    height: 4,
    row: 1,
  },
  Equal: {
    textRu: '=',
    textEn: '=',
    textShiftRu: '+',
    textShiftEn: '+',
    width: 6,
    height: 4,
    row: 1,
  },
  Backspace: {
    textRu: 'Backspace',
    textEn: 'Backspace',
    textShiftRu: 'Backspace',
    textShiftEn: 'Backspace',
    width: 17,
    height: 4,
    row: 1,
  },
  // second row
  Tab: {
    textRu: 'Tab',
    textEn: 'Tab',
    textShiftRu: 'Tab',
    textShiftEn: 'Tab',
    width: 11,
    height: 4,
    row: 2,
  },
  KeyQ: {
    textRu: 'й',
    textEn: 'q',
    textShiftRu: 'Й',
    textShiftEn: 'Q',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyW: {
    textRu: 'ц',
    textEn: 'w',
    textShiftRu: 'Ц',
    textShiftEn: 'W',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyE: {
    textRu: 'у',
    textEn: 'e',
    textShiftRu: 'У',
    textShiftEn: 'E',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyR: {
    textRu: 'к',
    textEn: 'r',
    textShiftRu: 'К',
    textShiftEn: 'R',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyT: {
    textRu: 'е',
    textEn: 't',
    textShiftRu: 'Е',
    textShiftEn: 'T',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyY: {
    textRu: 'н',
    textEn: 'y',
    textShiftRu: 'Н',
    textShiftEn: 'Y',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyU: {
    textRu: 'г',
    textEn: 'u',
    textShiftRu: 'Г',
    textShiftEn: 'U',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyI: {
    textRu: 'ш',
    textEn: 'i',
    textShiftRu: 'Ш',
    textShiftEn: 'I',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyO: {
    textRu: 'щ',
    textEn: 'o',
    textShiftRu: 'Щ',
    textShiftEn: 'O',
    width: 6,
    height: 4,
    row: 2,
  },
  KeyP: {
    textRu: 'з',
    textEn: 'p',
    textShiftRu: 'З',
    textShiftEn: 'P',
    width: 6,
    height: 4,
    row: 2,
  },
  BracketLeft: {
    textRu: 'х',
    textEn: '[',
    textShiftRu: 'Х',
    textShiftEn: '{',
    width: 6,
    height: 4,
    row: 2,
  },
  BracketRight: {
    textRu: 'ъ',
    textEn: ']',
    textShiftRu: 'Ъ',
    textShiftEn: '}',
    width: 6,
    height: 4,
    row: 2,
  },
  Backslash: {
    textRu: '\\',
    textEn: '\\',
    textShiftRu: '/',
    textShiftEn: '|',
    width: 12,
    height: 4,
    row: 2,
  },
  // third row
  CapsLock: {
    textRu: 'CapsLock',
    textEn: 'CapsLock',
    textShiftRu: 'CapsLock*',
    textShiftEn: 'CapsLock*',
    width: 13,
    height: 4,
    row: 3,
  },
  KeyA: {
    textRu: 'ф',
    textEn: 'a',
    textShiftRu: 'Ф',
    textShiftEn: 'A',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyS: {
    textRu: 'ы',
    textEn: 's',
    textShiftRu: 'Ы',
    textShiftEn: 'S',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyD: {
    textRu: 'в',
    textEn: 'd',
    textShiftRu: 'В',
    textShiftEn: 'D',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyF: {
    textRu: 'а',
    textEn: 'f',
    textShiftRu: 'А',
    textShiftEn: 'F',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyG: {
    textRu: 'п',
    textEn: 'g',
    textShiftRu: 'П',
    textShiftEn: 'G',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyH: {
    textRu: 'р',
    textEn: 'h',
    textShiftRu: 'Р',
    textShiftEn: 'H',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyJ: {
    textRu: 'о',
    textEn: 'j',
    textShiftRu: 'О',
    textShiftEn: 'J',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyK: {
    textRu: 'л',
    textEn: 'k',
    textShiftRu: 'Л',
    textShiftEn: 'K',
    width: 6,
    height: 4,
    row: 3,
  },
  KeyL: {
    textRu: 'д',
    textEn: 'l',
    textShiftRu: 'Д',
    textShiftEn: 'L',
    width: 6,
    height: 4,
    row: 3,
  },
  Semicolon: {
    textRu: 'ж',
    textEn: ';',
    textShiftRu: 'Ж',
    textShiftEn: ':',
    width: 6,
    height: 4,
    row: 3,
  },
  Quote: {
    textRu: 'э',
    textEn: "'",
    textShiftRu: 'Э',
    textShiftEn: '"',
    width: 6,
    height: 4,
    row: 3,
  },
  Enter: {
    textRu: 'Enter',
    textEn: 'Enter',
    textShiftRu: 'Enter',
    textShiftEn: 'Enter',
    width: 17,
    height: 4,
    row: 3,
  },
  // four row
  ShiftLeft: {
    textRu: 'Shift',
    textEn: 'Shift',
    textShiftRu: 'Shift',
    textShiftEn: 'Shift',
    width: 16,
    height: 4,
    row: 4,
  },
  KeyZ: {
    textRu: 'я',
    textEn: 'z',
    textShiftRu: 'Я',
    textShiftEn: 'Z',
    width: 6,
    height: 4,
    row: 4,
  },
  KeyX: {
    textRu: 'ч',
    textEn: 'x',
    textShiftRu: 'Ч',
    textShiftEn: 'X',
    width: 6,
    height: 4,
    row: 4,
  },
  KeyC: {
    textRu: 'с',
    textEn: 'c',
    textShiftRu: 'С',
    textShiftEn: 'C',
    width: 6,
    height: 4,
    row: 4,
  },
  KeyV: {
    textRu: 'м',
    textEn: 'v',
    textShiftRu: 'М',
    textShiftEn: 'V',
    width: 6,
    height: 4,
    row: 4,
  },
  KeyB: {
    textRu: 'и',
    textEn: 'b',
    textShiftRu: 'И',
    textShiftEn: 'B',
    width: 6,
    height: 4,
    row: 4,
  },
  KeyN: {
    textRu: 'т',
    textEn: 'n',
    textShiftRu: 'Т',
    textShiftEn: 'N',
    width: 6,
    height: 4,
    row: 4,
  },
  KeyM: {
    textRu: 'ь',
    textEn: 'm',
    textShiftRu: 'Ь',
    textShiftEn: 'M',
    width: 6,
    height: 4,
    row: 4,
  },
  Comma: {
    textRu: 'б',
    textEn: ',',
    textShiftRu: 'Б',
    textShiftEn: '<',
    width: 6,
    height: 4,
    row: 4,
  },
  Period: {
    textRu: 'ю',
    textEn: '.',
    textShiftRu: 'Ю',
    textShiftEn: '>',
    width: 6,
    height: 4,
    row: 4,
  },
  Slash: {
    textRu: '.',
    textEn: '/',
    textShiftRu: ',',
    textShiftEn: '?',
    width: 6,
    height: 4,
    row: 4,
  },
  ArrowUp: {
    textRu: '▲',
    textEn: '▲',
    textShiftRu: '▲',
    textShiftEn: '▲',
    width: 6,
    height: 4,
    row: 4,
  },
  ShiftRight: {
    textRu: 'Shift',
    textEn: 'Shift',
    textShiftRu: 'Shift',
    textShiftEn: 'Shift',
    width: 14,
    height: 4,
    row: 4,
  },
  // five row
  ControlLeft: {
    textRu: 'Ctrl',
    textEn: 'Ctrl',
    textShiftRu: 'Ctrl',
    textShiftEn: 'Ctrl',
    width: 10,
    height: 4,
    row: 5,
  },
  AltLeft: {
    textRu: 'Alt',
    textEn: 'Alt',
    textShiftRu: 'Alt',
    textShiftEn: 'Alt',
    width: 10,
    height: 4,
    row: 5,
  },
  Space: {
    textRu: 'Space',
    textEn: 'Space',
    textShiftRu: 'Space',
    textShiftEn: 'Space',
    width: 35,
    height: 4,
    row: 5,
  },
  AltRight: {
    textRu: 'Alt',
    textEn: 'Alt',
    textShiftRu: 'Alt',
    textShiftEn: 'Alt',
    width: 10,
    height: 4,
    row: 5,
  },
  ControlRight: {
    textRu: 'Ctrl',
    textEn: 'Ctrl',
    textShiftRu: 'Ctrl',
    textShiftEn: 'Ctrl',
    width: 10,
    height: 4,
    row: 5,
  },
  ArrowLeft: {
    textRu: '◄',
    textEn: '◄',
    textShiftRu: '◄',
    textShiftEn: '◄',
    width: 6,
    height: 4,
    row: 5,
  },
  ArrowDown: {
    textRu: '▼',
    textEn: '▼',
    textShiftRu: '▼',
    textShiftEn: '▼',
    width: 6,
    height: 4,
    row: 5,
  },
  ArrowRight: {
    textRu: '►',
    textEn: '►',
    textShiftRu: '►',
    textShiftEn: '►',
    width: 6,
    height: 4,
    row: 5,
  },
  // for lang-change
  Lang: {
    textRu: 'RU',
    textEn: 'EN',
    textShiftRu: 'RU',
    textShiftEn: 'EN',
    width: 7,
    height: 4,
    row: 5,
  },
};

export default keysObj;
